# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - master
  paths:
    include:
      - terraform/*

pool: linux

steps:
- task: TerraformTaskV2@2
  inputs:
    provider: 'aws'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/'
    backendServiceAWS: 'AWS'
    backendAWSBucketName: 'security-app-poc-backend'
    backendAWSKey: 'terraform.tfstate'

- task: TerraformTaskV2@2
  inputs:
    provider: 'aws'
    command: 'apply'
    workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/'
    environmentServiceNameAWS: 'AWS'