# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - master
  paths:
    exclude:
      - terraform/*

pool: linux

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'docker'
    repository: 'ravitejak541/goapp'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'

- task: SnykSecurityScan@1
  inputs:
    serviceConnectionEndpoint: 'synk'
    testType: 'container'
    dockerImageName: 'ravitejak541/goapp:$(Build.BuildId)'
    monitorWhen: 'always'
    failOnIssues: true

- task: replacetokens@4
  inputs:
    rootDirectory: '$(Build.SourcesDirectory)/kubernetes/'
    targetFiles: '**/*.yaml'
    encoding: 'auto'
    tokenPattern: 'octopus'
    writeBOM: true
    actionOnMissing: 'warn'
    keepToken: false
    actionOnNoFiles: 'continue'
    enableTransforms: false
    useLegacyPattern: false
    enableTelemetry: true

- task: CopyFiles@2
  inputs:
    SourceFolder: 'kubernetes/'
    Contents: '**/*.yaml'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'manifest'
    publishLocation: 'Container'